// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJCtnTJsMmEC5x5cLNk59j
// Component: 5li343VTku5c

"use client"; // ⚠️ Ajouté ici pour activer le rendu client ⚠️

import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/navigation";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/host";
import Switch from "../../Switch"; // plasmic-import: 6qn7xRegxK8t/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: wJCtnTJsMmEC5x5cLNk59j/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 5li343VTku5c/css

createPlasmicElementProxy;

function PlasmicHomepage(props) {
  const { overrides } = props;

  return (
    <React.Fragment>
      <Head></Head>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}>
          <section className={classNames(projectcss.all, sty.section)}>
            <h1 className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.__wab_text,
              sty.h1
            )}>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{
                  color: "#1378CA",
                  fontWeight: 900,
                  fontStyle: "italic",
                  textDecorationLine: "underline"
                }}
              >
                {"Welcome Thomas !"}
              </span>
            </h1>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img)}
              src={{
                src: "/plasmic/dashboard_app/images/dallE20250308170507AModernHighResolutionIconOfARocketDesignedWithVibrantColorsAndATransparentBackgroundTheRocketHasASleekFuturisticDesignWitPng.png",
                fullWidth: 1024,
                fullHeight: 1024
              }}
            />
            <Switch className={classNames("__wab_instance", sty._switch)} label={"Bouton Auto Destruction"} />
            <div className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{
                  color: "#1677D1",
                  fontStyle: "italic",
                  textDecorationLine: "underline"
                }}
              >
                {"Plasmic + Next.js + Supabase + Stripe"}
              </span>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

// ✅ Assure-toi bien d'exporter le composant par défaut
export default PlasmicHomepage;

/* prettier-ignore-end */
